name: overlapped_carousel
description: A simple carousel package with overlapped items.
version: 1.0.0
homepage: https://github.com/GeekyAnts/flutter-carousel

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
